SELECT ID_USUARIO, NOMBRE, NOMBRE_USUARIO, CLAVE, ID_SUPERVISOR, ID_USUARIO_CREADOR, ID_ROL 
    FROM USUARIO;
SELECT ID_ROL, DESCRIPCION 
  FROM ROL;
SELECT ID_ESTADO_EVALUACION, DESCRIPCION 
  FROM ESTADO_EVALUACION;
SELECT ID_PLANTILLA, FECHA_CREADA, ID_USUARIO_CREADOR 
  FROM PLANTILLA;
SELECT ID_PLANTILLA, ID_PUNTO_EVALUACION, DESCRIPCION 
  FROM PUNTO_EVALUACION ORDER BY ID_PLANTILLA, ID_PUNTO_EVALUACION;
SELECT ID_EVALUACION, ID_PLANTILLA, FECHA_CREADA, ID_SUPERVISOR, ID_REPRESENTANTE, ID_ESTADO_EVALUACION
  FROM EVALUACION;
SELECT ID_EVALUACION, ID_PLANTILLA, ID_PUNTO_EVALUACION, CUMPLE_PUNTO, ES_RECLAMADA, COMENTARIO 
  FROM RESPUESTA;


--  VER LOS REPRESENTANTES QUE SE REPORTAN AL SUPERVISOR ID = 2
SELECT ID_USUARIO, NOMBRE FROM USUARIO WHERE ID_SUPERVISOR = 2;

-- VER LOS DETALLES DE LA EVALUACION 1
SELECT PE.DESCRIPCION, CUMPLE_PUNTO, ES_RECLAMADA FROM RESPUESTA RP, PUNTO_EVALUACION PE WHERE ID_EVALUACION = 1 AND PE.ID_PUNTO_EVALUACION = RP.ID_PUNTO_EVALUACION;

